export const amenitiesHelper = [
    { id: 1, name: "Air conditioning" },
    { id: 2, name: "Arcade games" },
    { id: 3, name: "Baby bath" },
    { id: 4, name: "Baby monitor" },
    { id: 5, name: "Baby safety gates" },
    { id: 6, name: "Babysitter recommendations" },
    { id: 7, name: "Backyard" },
    { id: 8, name: "Baking sheet" },
    { id: 9, name: "Barbecue utensils" },
    { id: 10, name: "Bathtub" },
    { id: 11, name: "Batting cage" },
    { id: 12, name: "BBQ grill" },
    { id: 13, name: "Beach essentials" },
    { id: 14, name: "Bed linens" },
    { id: 15, name: "Bidet" },
    { id: 16, name: "Bikes" },
    { id: 17, name: "Blender" },
    { id: 18, name: "Board games" },
    { id: 19, name: "Boat slip" },
    { id: 20, name: "Body soap" },
    { id: 21, name: "Books and reading material" },
    { id: 22, name: "Bowling alley" },
    { id: 23, name: "Bread maker" },
    { id: 24, name: "Breakfast" },
    { id: 25, name: "Carbon monoxide alarm" },
    { id: 26, name: "Ceiling fan" },
    { id: 27, name: "Changing table" },
    { id: 28, name: "Children's playroom" },
    { id: 29, name: "Children’s bikes" },
    { id: 30, name: "Children’s books and toys" },
    { id: 31, name: "Children’s dinnerware" },
    { id: 32, name: "Cleaning available during stay" },
    { id: 33, name: "Cleaning products" },
    { id: 34, name: "Climbing wall" },
    { id: 35, name: "Clothing storage" },
    { id: 36, name: "Coffee" },
    { id: 37, name: "Coffee maker" },
    { id: 38, name: "Conditioner" },
    { id: 39, name: "Cooking basics" },
    { id: 40, name: "Crib" },
    { id: 41, name: "Dedicated workspace" },
    { id: 42, name: "Dining table" },
    { id: 43, name: "Dishes and silverware" },
    { id: 44, name: "Dishwasher" },
    { id: 45, name: "Dryer" },
    { id: 46, name: "Drying rack for clothing" },
    { id: 47, name: "Elevator" },
    { id: 48, name: "Essentials" },
    { id: 49, name: "Ethernet connection" },
    { id: 50, name: "EV charger" },
    { id: 51, name: "Exercise equipment" },
    { id: 52, name: "Extra pillows and blankets" },
    { id: 53, name: "Fire extinguisher" },
    { id: 54, name: "Fire pit" },
    { id: 55, name: "Fire screen" },
    { id: 56, name: "First aid kit" },
    { id: 57, name: "Free parking on premises" },
    { id: 58, name: "Free street parking" },
    { id: 59, name: "Freezer" },
    { id: 60, name: "Game console" },
    { id: 61, name: "Gym" },
    { id: 62, name: "Hair dryer" },
    { id: 63, name: "Hammock" },
    { id: 64, name: "Hangers" },
    { id: 65, name: "Heating" },
    { id: 66, name: "High chair" },
    { id: 67, name: "Hockey rink" },
    { id: 68, name: "Hot tub" },
    { id: 69, name: "Hot water" },
    { id: 70, name: "Hot water kettle" },
    { id: 71, name: "Indoor fireplace" },
    { id: 72, name: "Iron" },
    { id: 73, name: "Kayak" },
    { id: 74, name: "Kitchen" },
    { id: 75, name: "Kitchenette" },
    { id: 76, name: "Lake access" },
    { id: 77, name: "Laser tag" },
    { id: 78, name: "Laundromat nearby" },
    { id: 79, name: "Life size games" },
    { id: 80, name: "Long term stays allowed" },
    { id: 81, name: "Luggage dropoff allowed" },
    { id: 82, name: "Microwave" },
    { id: 83, name: "Mini fridge" },
    { id: 84, name: "Mini golf" },
    { id: 85, name: "Mosquito net" },
    { id: 86, name: "Movie theater" },
    { id: 87, name: "Outdoor dining area" },
    { id: 88, name: "Outdoor furniture" },
    { id: 89, name: "Outdoor kitchen" },
    { id: 90, name: "Outdoor playground" },
    { id: 91, name: "Outdoor shower" },
    { id: 92, name: "Outlet covers" },
    { id: 93, name: "Oven" },
    { id: 94, name: "Pack ’n play / Travel crib" },
    { id: 95, name: "Paid parking off premises" },
    { id: 96, name: "Paid parking on premises" },
    { id: 97, name: "Patio or balcony" },
    { id: 98, name: "Piano" },
    { id: 99, name: "Ping pong table" },
    { id: 100, name: "Pocket wifi" },
    { id: 101, name: "Pool" },
    { id: 102, name: "Pool table" },
    { id: 103, name: "Portable fans" },
    { id: 104, name: "Private entrance" },
    { id: 105, name: "Private living room" },
    { id: 106, name: "Record player" },
    { id: 107, name: "Refrigerator" },
    { id: 108, name: "Resort access" },
    { id: 109, name: "Rice Maker" },
    { id: 110, name: "Room - darkening shades" },
    { id: 111, name: "Safe" },
    { id: 112, name: "Sauna" },
    { id: 113, name: "Shampoo" },
    { id: 114, name: "Shower gel" },
    { id: 115, name: "Single level home" },
    { id: 116, name: "Skate ramp" },
    { id: 117, name: "Ski -in/Ski-out" },
    { id: 118, name: "Smoke alarm" },
    { id: 119, name: "Sound system" },
    { id: 120, name: "Stove" },
    { id: 121, name: "Sun loungers" },
    { id: 122, name: "Table corner guards" },
    { id: 123, name: "Theme room" },
    { id: 124, name: "Toaster" },
    { id: 125, name: "Trash compactor" },
    { id: 126, name: "TV" },
    { id: 127, name: "Washer" },
    { id: 128, name: "Waterfront" },
    { id: 129, name: "Wifi" },
    { id: 130, name: "Window guards" },
    { id: 131, name: "Wine glasses" }
];

